export enum Restriction {
  Vegan = "Vegan",
  Vegetarian = "Vegetarian",
  GlutenFree = "Gluten-Free",
  DairyFree = "Dairy-Free",
  Paleo = "Paleo",
  Ketogenic = "Ketogenic",
  LowCarb = "Low-Carb",
  SugarFree = "Sugar-Free",
  Halal = "Halal",
  Kosher = "Kosher",
  NonProcessed = "Non-Processed",
  NonGMO = "Non-GMO",
  WholeIngredients = "Whole Ingredients",
}
